"""empty message

Revision ID: 7e223c24e341
Revises: 6b28633f9d49
Create Date: 2016-04-23 18:52:34.249586

"""

# revision identifiers, used by Alembic.
revision = '7e223c24e341'
down_revision = '6b28633f9d49'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ratings', 'score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ratings', 'score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    ### end Alembic commands ###
